### ISSUE TITLE
bug report on ShopCore plugin, use CSSharp v.255

### ISSUE THREAD

**Issue by omega6428** [Ganter1234/Shop-Core#4]
19:07:33 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Text.Json.JsonReaderException: '"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 5 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(Stream utf8Json, JsonDocumentOptions options)
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.LoadJsonResources(String filePath) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 145
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.TryLoadResourceSet(String cultureName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 131
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.GetResourceSet(CultureInfo culture, Boolean tryParents) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 36
   at CounterStrikeSharp.API.Core.Translations.JsonStringLocalizer.get_Item(String name, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonStringLocalizer.cs:line 49
   at Shop.Shop.OpenShopMenu(CCSPlayerController player) in C:\Users\vital\Desktop\??????\?????????\????????? CS2 (csharp)\managed\Shop\Shop.cs:line 81
   at Shop.Shop.<OnConfigParsed>b__35_1(CCSPlayerController player, CommandInfo _) in C:\Users\vital\Desktop\??????\?????????\????????? CS2 (csharp)\managed\Shop\Shop.cs:line 888
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 159
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by Ganter1234** [comment]
Send your config file

**Comment by omega6428** [comment]
{
	"DatabaseHost": "localhost",
	"DatabasePort": 3306,
	"DatabaseUser": "root",
	"DatabasePassword": "admin",
	"DatabaseName": "database",
	"Commands": "css_shop;css_store",
	"UseCenterMenu": false,
	"StartCredits": 0,
	"TransCreditsPercent": 5,
	"AdminFlag": "@css/root"
}

that my shop.json , database write sucesfully with tables but i get this error on server but nothing appear in the game
i use your default config with my database usser/pass
i want to use this plugin for Stimayak SHOP modules (HP, HP regen, etc) to create a RPG mod CS2 server
please tell what i need else than CSSharp and metamod 2?

**Comment by Ganter1234** [comment]
Ok send please folder lang, maybe i something skipped

**Comment by omega6428** [comment]
[en.json](https://github.com/user-attachments/files/16643721/en.json)
[ru.json](https://github.com/user-attachments/files/16643722/ru.json)

that's only files i found in lang..i use english windows 10 Pro 22H2
so please test at you and tell me what i missed?

**Comment by omega6428** [comment]
Hi, i see that video works :https://youtu.be/JBN8xz4hGD0
please tell me how i do wrong? i use list of dependencies:
windows 10Pro22H2 English language
MMSOURCE v2.0 1313
CSSharps v.255
Mysql server standard that record all tables 
when i type css_shop in console, server crash with error show in first issue open post
i need Russian language system to work? no work in english version of windows?

**Comment by Ganter1234** [comment]
So, i found reason of problem, use that translate file, in next update i upload this on archive
[en.json](https://github.com/user-attachments/files/16677928/en.json)

**Comment by omega6428** [comment]
Thank you for help, now run fine but only in russian..

**Comment by omega6428** [comment]
Thank You, now shop works, but no one module by STIMAYK works, record in
database but nothing changed.. please test in game one of health/health
regeneration module by stimayk and tell me if i messed something.. no one
warnings/errors appear in server console css_plugins list show me all
loaded but nothing happened in the game after buy Health example.. i also
opened issue to Stimayk about no working modules

**Comment by Ganter1234** [comment]
Fix on new update
